/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAccountsRouteImport } from './routes/app/accounts'
import { Route as AppAddEntriesRouteImport } from './routes/app/add-entries'
import { Route as AppChasingRouteImport } from './routes/app/chasing'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppInvoicesRouteImport } from './routes/app/invoices'
import { Route as AppPaymentsRouteImport } from './routes/app/payments'
import { Route as AppReportsRouteImport } from './routes/app/reports'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiV1ChasesRouteImport } from './routes/api/v1/chases'
import { Route as AppAccountsIndexRouteImport } from './routes/app/accounts.index'
import { Route as AppAccountsAccountIdRouteImport } from './routes/app/accounts.$accountId'
import { Route as ApiV1AccountsIndexRouteImport } from './routes/api/v1/accounts/index'
import { Route as ApiV1DashboardChaseQueueRouteImport } from './routes/api/v1/dashboard/chase-queue'
import { Route as ApiV1DashboardSummaryRouteImport } from './routes/api/v1/dashboard/summary'
import { Route as ApiV1AccountsAccountIdIndexRouteImport } from './routes/api/v1/accounts/$accountId/index'
import { Route as ApiV1AccountsAccountIdActivityRouteImport } from './routes/api/v1/accounts/$accountId/activity'
import { Route as ApiV1AccountsAccountIdArchiveRouteImport } from './routes/api/v1/accounts/$accountId/archive'
import { Route as ApiV1AccountsAccountIdChasingSettingsRouteImport } from './routes/api/v1/accounts/$accountId/chasing-settings'
import { Route as ApiV1AccountsAccountIdEscalationRouteImport } from './routes/api/v1/accounts/$accountId/escalation'
import { Route as ApiV1AccountsAccountIdInvoicesRouteImport } from './routes/api/v1/accounts/$accountId/invoices'
import { Route as ApiV1AccountsAccountIdPauseRouteImport } from './routes/api/v1/accounts/$accountId/pause'
import { Route as ApiV1AccountsAccountIdPaymentsRouteImport } from './routes/api/v1/accounts/$accountId/payments'
import { Route as ApiV1AccountsAccountIdRestoreRouteImport } from './routes/api/v1/accounts/$accountId/restore'
import { Route as ApiV1AccountsAccountIdResumeRouteImport } from './routes/api/v1/accounts/$accountId/resume'
import { Route as ApiV1AccountsAccountIdContactsIndexRouteImport } from './routes/api/v1/accounts/$accountId/contacts/index'
import { Route as ApiV1AccountsAccountIdContactsContactIdRouteImport } from './routes/api/v1/accounts/$accountId/contacts/$contactId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppAddEntriesRoute = AppAddEntriesRouteImport.update({
  id: '/add-entries',
  path: '/add-entries',
  getParentRoute: () => AppRoute,
} as any)
const AppChasingRoute = AppChasingRouteImport.update({
  id: '/chasing',
  path: '/chasing',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ChasesRoute = ApiV1ChasesRouteImport.update({
  id: '/api/v1/chases',
  path: '/api/v1/chases',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountsRoute,
} as any)
const AppAccountsAccountIdRoute = AppAccountsAccountIdRouteImport.update({
  id: '/$accountId',
  path: '/$accountId',
  getParentRoute: () => AppAccountsRoute,
} as any)
const ApiV1AccountsIndexRoute = ApiV1AccountsIndexRouteImport.update({
  id: '/api/v1/accounts/',
  path: '/api/v1/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DashboardChaseQueueRoute =
  ApiV1DashboardChaseQueueRouteImport.update({
    id: '/api/v1/dashboard/chase-queue',
    path: '/api/v1/dashboard/chase-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1DashboardSummaryRoute = ApiV1DashboardSummaryRouteImport.update({
  id: '/api/v1/dashboard/summary',
  path: '/api/v1/dashboard/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AccountsAccountIdIndexRoute =
  ApiV1AccountsAccountIdIndexRouteImport.update({
    id: '/api/v1/accounts/$accountId/',
    path: '/api/v1/accounts/$accountId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AccountsAccountIdActivityRoute =
  ApiV1AccountsAccountIdActivityRouteImport.update({
    id: '/api/v1/accounts/$accountId/activity',
    path: '/api/v1/accounts/$accountId/activity',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AccountsAccountIdArchiveRoute =
  ApiV1AccountsAccountIdArchiveRouteImport.update({
    id: '/api/v1/accounts/$accountId/archive',
    path: '/api/v1/accounts/$accountId/archive',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AccountsAccountIdChasingSettingsRoute =
  ApiV1AccountsAccountIdChasingSettingsRouteImport.update({
    id: '/api/v1/accounts/$accountId/chasing-settings',
    path: '/api/v1/accounts/$accountId/chasing-settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AccountsAccountIdEscalationRoute =
  ApiV1AccountsAccountIdEscalationRouteImport.update({
    id: '/api/v1/accounts/$accountId/escalation',
    path: '/api/v1/accounts/$accountId/escalation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AccountsAccountIdInvoicesRoute =
  ApiV1AccountsAccountIdInvoicesRouteImport.update({
    id: '/api/v1/accounts/$accountId/invoices',
    path: '/api/v1/accounts/$accountId/invoices',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AccountsAccountIdPauseRoute =
  ApiV1AccountsAccountIdPauseRouteImport.update({
    id: '/api/v1/accounts/$accountId/pause',
    path: '/api/v1/accounts/$accountId/pause',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AccountsAccountIdPaymentsRoute =
  ApiV1AccountsAccountIdPaymentsRouteImport.update({
    id: '/api/v1/accounts/$accountId/payments',
    path: '/api/v1/accounts/$accountId/payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AccountsAccountIdRestoreRoute =
  ApiV1AccountsAccountIdRestoreRouteImport.update({
    id: '/api/v1/accounts/$accountId/restore',
    path: '/api/v1/accounts/$accountId/restore',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AccountsAccountIdResumeRoute =
  ApiV1AccountsAccountIdResumeRouteImport.update({
    id: '/api/v1/accounts/$accountId/resume',
    path: '/api/v1/accounts/$accountId/resume',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AccountsAccountIdContactsIndexRoute =
  ApiV1AccountsAccountIdContactsIndexRouteImport.update({
    id: '/api/v1/accounts/$accountId/contacts/',
    path: '/api/v1/accounts/$accountId/contacts/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AccountsAccountIdContactsContactIdRoute =
  ApiV1AccountsAccountIdContactsContactIdRouteImport.update({
    id: '/api/v1/accounts/$accountId/contacts/$contactId',
    path: '/api/v1/accounts/$accountId/contacts/$contactId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/accounts': typeof AppAccountsRouteWithChildren
  '/app/add-entries': typeof AppAddEntriesRoute
  '/app/chasing': typeof AppChasingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
  '/api/v1/chases': typeof ApiV1ChasesRoute
  '/app/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/app/accounts/': typeof AppAccountsIndexRoute
  '/api/v1/dashboard/chase-queue': typeof ApiV1DashboardChaseQueueRoute
  '/api/v1/dashboard/summary': typeof ApiV1DashboardSummaryRoute
  '/api/v1/accounts/': typeof ApiV1AccountsIndexRoute
  '/api/v1/accounts/$accountId/activity': typeof ApiV1AccountsAccountIdActivityRoute
  '/api/v1/accounts/$accountId/archive': typeof ApiV1AccountsAccountIdArchiveRoute
  '/api/v1/accounts/$accountId/chasing-settings': typeof ApiV1AccountsAccountIdChasingSettingsRoute
  '/api/v1/accounts/$accountId/escalation': typeof ApiV1AccountsAccountIdEscalationRoute
  '/api/v1/accounts/$accountId/invoices': typeof ApiV1AccountsAccountIdInvoicesRoute
  '/api/v1/accounts/$accountId/pause': typeof ApiV1AccountsAccountIdPauseRoute
  '/api/v1/accounts/$accountId/payments': typeof ApiV1AccountsAccountIdPaymentsRoute
  '/api/v1/accounts/$accountId/restore': typeof ApiV1AccountsAccountIdRestoreRoute
  '/api/v1/accounts/$accountId/resume': typeof ApiV1AccountsAccountIdResumeRoute
  '/api/v1/accounts/$accountId/': typeof ApiV1AccountsAccountIdIndexRoute
  '/api/v1/accounts/$accountId/contacts/$contactId': typeof ApiV1AccountsAccountIdContactsContactIdRoute
  '/api/v1/accounts/$accountId/contacts/': typeof ApiV1AccountsAccountIdContactsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/add-entries': typeof AppAddEntriesRoute
  '/app/chasing': typeof AppChasingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app': typeof AppIndexRoute
  '/api/v1/chases': typeof ApiV1ChasesRoute
  '/app/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/app/accounts': typeof AppAccountsIndexRoute
  '/api/v1/dashboard/chase-queue': typeof ApiV1DashboardChaseQueueRoute
  '/api/v1/dashboard/summary': typeof ApiV1DashboardSummaryRoute
  '/api/v1/accounts': typeof ApiV1AccountsIndexRoute
  '/api/v1/accounts/$accountId/activity': typeof ApiV1AccountsAccountIdActivityRoute
  '/api/v1/accounts/$accountId/archive': typeof ApiV1AccountsAccountIdArchiveRoute
  '/api/v1/accounts/$accountId/chasing-settings': typeof ApiV1AccountsAccountIdChasingSettingsRoute
  '/api/v1/accounts/$accountId/escalation': typeof ApiV1AccountsAccountIdEscalationRoute
  '/api/v1/accounts/$accountId/invoices': typeof ApiV1AccountsAccountIdInvoicesRoute
  '/api/v1/accounts/$accountId/pause': typeof ApiV1AccountsAccountIdPauseRoute
  '/api/v1/accounts/$accountId/payments': typeof ApiV1AccountsAccountIdPaymentsRoute
  '/api/v1/accounts/$accountId/restore': typeof ApiV1AccountsAccountIdRestoreRoute
  '/api/v1/accounts/$accountId/resume': typeof ApiV1AccountsAccountIdResumeRoute
  '/api/v1/accounts/$accountId': typeof ApiV1AccountsAccountIdIndexRoute
  '/api/v1/accounts/$accountId/contacts/$contactId': typeof ApiV1AccountsAccountIdContactsContactIdRoute
  '/api/v1/accounts/$accountId/contacts': typeof ApiV1AccountsAccountIdContactsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/accounts': typeof AppAccountsRouteWithChildren
  '/app/add-entries': typeof AppAddEntriesRoute
  '/app/chasing': typeof AppChasingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
  '/api/v1/chases': typeof ApiV1ChasesRoute
  '/app/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/app/accounts/': typeof AppAccountsIndexRoute
  '/api/v1/dashboard/chase-queue': typeof ApiV1DashboardChaseQueueRoute
  '/api/v1/dashboard/summary': typeof ApiV1DashboardSummaryRoute
  '/api/v1/accounts/': typeof ApiV1AccountsIndexRoute
  '/api/v1/accounts/$accountId/activity': typeof ApiV1AccountsAccountIdActivityRoute
  '/api/v1/accounts/$accountId/archive': typeof ApiV1AccountsAccountIdArchiveRoute
  '/api/v1/accounts/$accountId/chasing-settings': typeof ApiV1AccountsAccountIdChasingSettingsRoute
  '/api/v1/accounts/$accountId/escalation': typeof ApiV1AccountsAccountIdEscalationRoute
  '/api/v1/accounts/$accountId/invoices': typeof ApiV1AccountsAccountIdInvoicesRoute
  '/api/v1/accounts/$accountId/pause': typeof ApiV1AccountsAccountIdPauseRoute
  '/api/v1/accounts/$accountId/payments': typeof ApiV1AccountsAccountIdPaymentsRoute
  '/api/v1/accounts/$accountId/restore': typeof ApiV1AccountsAccountIdRestoreRoute
  '/api/v1/accounts/$accountId/resume': typeof ApiV1AccountsAccountIdResumeRoute
  '/api/v1/accounts/$accountId/': typeof ApiV1AccountsAccountIdIndexRoute
  '/api/v1/accounts/$accountId/contacts/$contactId': typeof ApiV1AccountsAccountIdContactsContactIdRoute
  '/api/v1/accounts/$accountId/contacts/': typeof ApiV1AccountsAccountIdContactsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/accounts'
    | '/app/add-entries'
    | '/app/chasing'
    | '/app/dashboard'
    | '/app/invoices'
    | '/app/payments'
    | '/app/reports'
    | '/app/settings'
    | '/auth/callback'
    | '/app/'
    | '/api/v1/chases'
    | '/app/accounts/$accountId'
    | '/app/accounts/'
    | '/api/v1/dashboard/chase-queue'
    | '/api/v1/dashboard/summary'
    | '/api/v1/accounts/'
    | '/api/v1/accounts/$accountId/activity'
    | '/api/v1/accounts/$accountId/archive'
    | '/api/v1/accounts/$accountId/chasing-settings'
    | '/api/v1/accounts/$accountId/escalation'
    | '/api/v1/accounts/$accountId/invoices'
    | '/api/v1/accounts/$accountId/pause'
    | '/api/v1/accounts/$accountId/payments'
    | '/api/v1/accounts/$accountId/restore'
    | '/api/v1/accounts/$accountId/resume'
    | '/api/v1/accounts/$accountId/'
    | '/api/v1/accounts/$accountId/contacts/$contactId'
    | '/api/v1/accounts/$accountId/contacts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/add-entries'
    | '/app/chasing'
    | '/app/dashboard'
    | '/app/invoices'
    | '/app/payments'
    | '/app/reports'
    | '/app/settings'
    | '/auth/callback'
    | '/app'
    | '/api/v1/chases'
    | '/app/accounts/$accountId'
    | '/app/accounts'
    | '/api/v1/dashboard/chase-queue'
    | '/api/v1/dashboard/summary'
    | '/api/v1/accounts'
    | '/api/v1/accounts/$accountId/activity'
    | '/api/v1/accounts/$accountId/archive'
    | '/api/v1/accounts/$accountId/chasing-settings'
    | '/api/v1/accounts/$accountId/escalation'
    | '/api/v1/accounts/$accountId/invoices'
    | '/api/v1/accounts/$accountId/pause'
    | '/api/v1/accounts/$accountId/payments'
    | '/api/v1/accounts/$accountId/restore'
    | '/api/v1/accounts/$accountId/resume'
    | '/api/v1/accounts/$accountId'
    | '/api/v1/accounts/$accountId/contacts/$contactId'
    | '/api/v1/accounts/$accountId/contacts'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/accounts'
    | '/app/add-entries'
    | '/app/chasing'
    | '/app/dashboard'
    | '/app/invoices'
    | '/app/payments'
    | '/app/reports'
    | '/app/settings'
    | '/auth/callback'
    | '/app/'
    | '/api/v1/chases'
    | '/app/accounts/$accountId'
    | '/app/accounts/'
    | '/api/v1/dashboard/chase-queue'
    | '/api/v1/dashboard/summary'
    | '/api/v1/accounts/'
    | '/api/v1/accounts/$accountId/activity'
    | '/api/v1/accounts/$accountId/archive'
    | '/api/v1/accounts/$accountId/chasing-settings'
    | '/api/v1/accounts/$accountId/escalation'
    | '/api/v1/accounts/$accountId/invoices'
    | '/api/v1/accounts/$accountId/pause'
    | '/api/v1/accounts/$accountId/payments'
    | '/api/v1/accounts/$accountId/restore'
    | '/api/v1/accounts/$accountId/resume'
    | '/api/v1/accounts/$accountId/'
    | '/api/v1/accounts/$accountId/contacts/$contactId'
    | '/api/v1/accounts/$accountId/contacts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiV1ChasesRoute: typeof ApiV1ChasesRoute
  ApiV1DashboardChaseQueueRoute: typeof ApiV1DashboardChaseQueueRoute
  ApiV1DashboardSummaryRoute: typeof ApiV1DashboardSummaryRoute
  ApiV1AccountsIndexRoute: typeof ApiV1AccountsIndexRoute
  ApiV1AccountsAccountIdActivityRoute: typeof ApiV1AccountsAccountIdActivityRoute
  ApiV1AccountsAccountIdArchiveRoute: typeof ApiV1AccountsAccountIdArchiveRoute
  ApiV1AccountsAccountIdChasingSettingsRoute: typeof ApiV1AccountsAccountIdChasingSettingsRoute
  ApiV1AccountsAccountIdEscalationRoute: typeof ApiV1AccountsAccountIdEscalationRoute
  ApiV1AccountsAccountIdInvoicesRoute: typeof ApiV1AccountsAccountIdInvoicesRoute
  ApiV1AccountsAccountIdPauseRoute: typeof ApiV1AccountsAccountIdPauseRoute
  ApiV1AccountsAccountIdPaymentsRoute: typeof ApiV1AccountsAccountIdPaymentsRoute
  ApiV1AccountsAccountIdRestoreRoute: typeof ApiV1AccountsAccountIdRestoreRoute
  ApiV1AccountsAccountIdResumeRoute: typeof ApiV1AccountsAccountIdResumeRoute
  ApiV1AccountsAccountIdIndexRoute: typeof ApiV1AccountsAccountIdIndexRoute
  ApiV1AccountsAccountIdContactsContactIdRoute: typeof ApiV1AccountsAccountIdContactsContactIdRoute
  ApiV1AccountsAccountIdContactsIndexRoute: typeof ApiV1AccountsAccountIdContactsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accounts': {
      id: '/app/accounts'
      path: '/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/add-entries': {
      id: '/app/add-entries'
      path: '/add-entries'
      fullPath: '/app/add-entries'
      preLoaderRoute: typeof AppAddEntriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chasing': {
      id: '/app/chasing'
      path: '/chasing'
      fullPath: '/app/chasing'
      preLoaderRoute: typeof AppChasingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/chases': {
      id: '/api/v1/chases'
      path: '/api/v1/chases'
      fullPath: '/api/v1/chases'
      preLoaderRoute: typeof ApiV1ChasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/accounts/': {
      id: '/app/accounts/'
      path: '/'
      fullPath: '/app/accounts/'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/app/accounts/$accountId': {
      id: '/app/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/app/accounts/$accountId'
      preLoaderRoute: typeof AppAccountsAccountIdRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/api/v1/accounts/': {
      id: '/api/v1/accounts/'
      path: '/api/v1/accounts'
      fullPath: '/api/v1/accounts/'
      preLoaderRoute: typeof ApiV1AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/dashboard/chase-queue': {
      id: '/api/v1/dashboard/chase-queue'
      path: '/api/v1/dashboard/chase-queue'
      fullPath: '/api/v1/dashboard/chase-queue'
      preLoaderRoute: typeof ApiV1DashboardChaseQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/dashboard/summary': {
      id: '/api/v1/dashboard/summary'
      path: '/api/v1/dashboard/summary'
      fullPath: '/api/v1/dashboard/summary'
      preLoaderRoute: typeof ApiV1DashboardSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/accounts/$accountId/': {
      id: '/api/v1/accounts/$accountId/'
      path: '/api/v1/accounts/$accountId'
      fullPath: '/api/v1/accounts/$accountId/'
      preLoaderRoute: typeof ApiV1AccountsAccountIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/accounts/$accountId/activity': {
      id: '/api/v1/accounts/$accountId/activity'
      path: '/api/v1/accounts/$accountId/activity'
      fullPath: '/api/v1/accounts/$accountId/activity'
      preLoaderRoute: typeof ApiV1AccountsAccountIdActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/accounts/$accountId/archive': {
      id: '/api/v1/accounts/$accountId/archive'
      path: '/api/v1/accounts/$accountId/archive'
      fullPath: '/api/v1/accounts/$accountId/archive'
      preLoaderRoute: typeof ApiV1AccountsAccountIdArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/accounts/$accountId/chasing-settings': {
      id: '/api/v1/accounts/$accountId/chasing-settings'
      path: '/api/v1/accounts/$accountId/chasing-settings'
      fullPath: '/api/v1/accounts/$accountId/chasing-settings'
      preLoaderRoute: typeof ApiV1AccountsAccountIdChasingSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/accounts/$accountId/escalation': {
      id: '/api/v1/accounts/$accountId/escalation'
      path: '/api/v1/accounts/$accountId/escalation'
      fullPath: '/api/v1/accounts/$accountId/escalation'
      preLoaderRoute: typeof ApiV1AccountsAccountIdEscalationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/accounts/$accountId/invoices': {
      id: '/api/v1/accounts/$accountId/invoices'
      path: '/api/v1/accounts/$accountId/invoices'
      fullPath: '/api/v1/accounts/$accountId/invoices'
      preLoaderRoute: typeof ApiV1AccountsAccountIdInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/accounts/$accountId/pause': {
      id: '/api/v1/accounts/$accountId/pause'
      path: '/api/v1/accounts/$accountId/pause'
      fullPath: '/api/v1/accounts/$accountId/pause'
      preLoaderRoute: typeof ApiV1AccountsAccountIdPauseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/accounts/$accountId/payments': {
      id: '/api/v1/accounts/$accountId/payments'
      path: '/api/v1/accounts/$accountId/payments'
      fullPath: '/api/v1/accounts/$accountId/payments'
      preLoaderRoute: typeof ApiV1AccountsAccountIdPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/accounts/$accountId/restore': {
      id: '/api/v1/accounts/$accountId/restore'
      path: '/api/v1/accounts/$accountId/restore'
      fullPath: '/api/v1/accounts/$accountId/restore'
      preLoaderRoute: typeof ApiV1AccountsAccountIdRestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/accounts/$accountId/resume': {
      id: '/api/v1/accounts/$accountId/resume'
      path: '/api/v1/accounts/$accountId/resume'
      fullPath: '/api/v1/accounts/$accountId/resume'
      preLoaderRoute: typeof ApiV1AccountsAccountIdResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/accounts/$accountId/contacts/': {
      id: '/api/v1/accounts/$accountId/contacts/'
      path: '/api/v1/accounts/$accountId/contacts'
      fullPath: '/api/v1/accounts/$accountId/contacts/'
      preLoaderRoute: typeof ApiV1AccountsAccountIdContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/accounts/$accountId/contacts/$contactId': {
      id: '/api/v1/accounts/$accountId/contacts/$contactId'
      path: '/api/v1/accounts/$accountId/contacts/$contactId'
      fullPath: '/api/v1/accounts/$accountId/contacts/$contactId'
      preLoaderRoute: typeof ApiV1AccountsAccountIdContactsContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAccountsRouteChildren {
  AppAccountsAccountIdRoute: typeof AppAccountsAccountIdRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
}

const AppAccountsRouteChildren: AppAccountsRouteChildren = {
  AppAccountsAccountIdRoute: AppAccountsAccountIdRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
}

const AppAccountsRouteWithChildren = AppAccountsRoute._addFileChildren(
  AppAccountsRouteChildren,
)

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRouteWithChildren
  AppAddEntriesRoute: typeof AppAddEntriesRoute
  AppChasingRoute: typeof AppChasingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRouteWithChildren,
  AppAddEntriesRoute: AppAddEntriesRoute,
  AppChasingRoute: AppChasingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiV1ChasesRoute: ApiV1ChasesRoute,
  ApiV1DashboardChaseQueueRoute: ApiV1DashboardChaseQueueRoute,
  ApiV1DashboardSummaryRoute: ApiV1DashboardSummaryRoute,
  ApiV1AccountsIndexRoute: ApiV1AccountsIndexRoute,
  ApiV1AccountsAccountIdActivityRoute: ApiV1AccountsAccountIdActivityRoute,
  ApiV1AccountsAccountIdArchiveRoute: ApiV1AccountsAccountIdArchiveRoute,
  ApiV1AccountsAccountIdChasingSettingsRoute:
    ApiV1AccountsAccountIdChasingSettingsRoute,
  ApiV1AccountsAccountIdEscalationRoute: ApiV1AccountsAccountIdEscalationRoute,
  ApiV1AccountsAccountIdInvoicesRoute: ApiV1AccountsAccountIdInvoicesRoute,
  ApiV1AccountsAccountIdPauseRoute: ApiV1AccountsAccountIdPauseRoute,
  ApiV1AccountsAccountIdPaymentsRoute: ApiV1AccountsAccountIdPaymentsRoute,
  ApiV1AccountsAccountIdRestoreRoute: ApiV1AccountsAccountIdRestoreRoute,
  ApiV1AccountsAccountIdResumeRoute: ApiV1AccountsAccountIdResumeRoute,
  ApiV1AccountsAccountIdIndexRoute: ApiV1AccountsAccountIdIndexRoute,
  ApiV1AccountsAccountIdContactsContactIdRoute:
    ApiV1AccountsAccountIdContactsContactIdRoute,
  ApiV1AccountsAccountIdContactsIndexRoute:
    ApiV1AccountsAccountIdContactsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
